version: "3"
services:
  genesis:
    container_name: "genesis_catbot"
    build: .
    # volumes:
    #   - .:/home/genesis/src
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Jakarta
      - DEBIAN_FRONTEND=noninteractive
      - FLASK_APP=/home/genesis/src/run.py
      - FLASK_DEBUG=1
      - ENV=devel
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - QA_API_URL=${QA_API_URL}
    # command: flask run --host=0.0.0.0 --port=8080